services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.8-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - net

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    env_file:
      - .env
    environment:
      - DEFAULT_EMAIL=${EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
      - VIRTUAL_HOST=${HOST_NAMES}
      - LETSENCRYPT_HOST=${HOST_NAMES}
      - LETSENCRYPT_EMAIL=${EMAIL}
    pre_stop:
      - command: touch /tmp/drain && sleep 10
    healthcheck:
      test: test ! -f /tmp/drain
      interval: 5s
      retries: 1
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme
    networks:
      - net

networks:
  net:

volumes:
  html:
  certs:
  acme: