services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.8-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - net

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    env_file:
      - .env.prod
    environment:
      - DEFAULT_EMAIL=${EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${APP_PORT}
    env_file:
      - .env.prod
    environment:
      - HOST=${APP_HOST}
      - PORT=${APP_PORT}
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
      - VIRTUAL_HOST=${HOST_NAMES}
      - VIRTUAL_PORT=${APP_PORT}
      - LETSENCRYPT_HOST=${HOST_NAMES}
      - LETSENCRYPT_EMAIL=${EMAIL}
    pre_stop:
      - command: touch /tmp/drain && sleep 60
    healthcheck:
      test: ["CMD-SHELL", "test ! -f /tmp/drain && curl -fs - http://localhost:3000/healthcheck || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - net

networks:
  net:

volumes:
  html:
  certs:
  acme: