name: Deploy App

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch: 
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@5.0.0
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
    - name: Pull and restart containers
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd apps/ui-finder
          git pull origin main
          docker compose build app
          docker rollout app
        EOF